### PR TITLE
Use standard properties for maven-compiler-plugin

### PR DESCRIPTION
**Pull request by ctubbsii**
* Use standard properties to set maven-compiler-plugin's source and target options
* Add the maven.compiler.release property, but only when building with a JDK that supports it, or when building in Eclipse

### CODE REVIEW

**Comment by hazendaz** [comment]
Not sure m2e fully supports that except in latest and m2e is rather fragile for last year and older releases of eclipse would be problematic.  I would leave that bit out for now.  Totally agree on the other since those flags are used by many plugins.  But this will all be changing soon.  See my fork on master branch if I recall.  Completely reworking the build to drop jdk 8 from it.  It's not done so this is certainly ok step in right direction but would leave m2e out.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Christopher Tubbs ***@***.***>
Sent: Thursday, March 23, 2023 10:33:46 PM
To: mathieucarbou/license-maven-plugin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mathieucarbou/license-maven-plugin] Use standard properties for maven-compiler-plugin (PR #522)


  *   Use standard properties to set maven-compiler-plugin's source and target options
  *   Add the maven.compiler.release property, but only when building with a JDK that supports it, or when building in Eclipse

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/mathieucarbou/license-maven-plugin/pull/522<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmathieucarbou%2Flicense-maven-plugin%2Fpull%2F522&data=05%7C01%7C%7C9be9f7e800c04054f6f708db2c103212%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638152220288801660%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=98uG2lA1PuItv60XmuwP%2FVNyqtfokUqBBJBuVuATics%3D&reserved=0>

Commit Summary

  *   8d12140<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmathieucarbou%2Flicense-maven-plugin%2Fpull%2F522%2Fcommits%2F8d12140f3977146312bf23b23509f827e9234ca6&data=05%7C01%7C%7C9be9f7e800c04054f6f708db2c103212%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638152220288801660%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RDmYejq7MwEtiHIpbiODGZehICYXk%2BeNyK%2BPp8Om9NE%3D&reserved=0> Use standard properties for maven-compiler-plugin

File Changes

(1 file<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmathieucarbou%2Flicense-maven-plugin%2Fpull%2F522%2Ffiles&data=05%7C01%7C%7C9be9f7e800c04054f6f708db2c103212%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638152220288801660%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kU3Ojr%2BslWzqJUydjX1BGSeV1QIXlpzh%2FfuEwnQPEjo%3D&reserved=0>)

  *   M pom.xml<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmathieucarbou%2Flicense-maven-plugin%2Fpull%2F522%2Ffiles%23diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8&data=05%7C01%7C%7C9be9f7e800c04054f6f708db2c103212%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638152220288801660%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=j73Y4SbQwnBIWTXNssdiShe3lpfJ0Q2oD6pvwUS1zIQ%3D&reserved=0> (30)

Patch Links:

  *   https://github.com/mathieucarbou/license-maven-plugin/pull/522.patch<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmathieucarbou%2Flicense-maven-plugin%2Fpull%2F522.patch&data=05%7C01%7C%7C9be9f7e800c04054f6f708db2c103212%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638152220288801660%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=UI1xqu52WOkVDktm0xrH%2B%2B21k0DQxf4DtRqz14DDBOI%3D&reserved=0>
  *   https://github.com/mathieucarbou/license-maven-plugin/pull/522.diff<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmathieucarbou%2Flicense-maven-plugin%2Fpull%2F522.diff&data=05%7C01%7C%7C9be9f7e800c04054f6f708db2c103212%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638152220288801660%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tZWxmELevQFgGP5ZTQfh49DTOInuhS8zIwHrhhtxO4I%3D&reserved=0>

**Comment by hazendaz** [comment]
Also good to look at that as that shows that other thread on formatter were someone wanted proof maven 3.3.9 worked so it does that plus drops jdk 8 to show consumer usage.  For whatever reason windows failed for me so I didn't progress further or have time yet but it's nearly up to date as of yesterday night.  I had also tried jdk 21 but not ready on that either.  I'm live doing similar thing on spotbugs maven plugin as well.

By all means don't let that hold this up.  Again my only concern here is m2e.  After living that for last year with nearly every eclipse broken, I don't much trust their stability and older eclipse m2e won't work the same.  It's much better now but I know many have not upgraded.  At work we still use 2022-03, due entirely to m2e and it certainly doesn't support release prop yet then.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ctubbsii** [comment]
> Not sure m2e fully supports that except in latest and m2e is rather fragile for last year and older releases of eclipse would be problematic. I would leave that bit out for now.

The m2e profile only activates if Eclipse M2E environment is detected. This works quite well, and forces Eclipse to use the correct settings for the project. I've used it on multiple projects before. In versions of Eclipse that understand this flag, it uses it to automatically set the compiler compliance level in Eclipse for the imported Maven project. If it's on a version of Eclipse that doesn't support it, it is simply ignored by the Eclipse compiler.

**Comment by hazendaz** [comment]
sorry lost track of this, merging as soon as build completes.

**Review by hazendaz — APPROVED** [review]

**Pull request merged**
